apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit-order-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limit-order-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: limit-order-svc
    spec:
      containers:
        - name: limit-order-svc
          image: docker.io/library/limit-order-svc
          ports:
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Never
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600